# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: af7d59c7ee824853408435fef2714ca9ca42f37a7b5035cb4d7e25376e7e1ad6078aff9dee603e3463af0240573f1fb3dde0181dccd1bf1e7a4312e17a6c9f9f

test:
  secret_key_base: b1199609f2fe48b89ca60c1f892f803b3112f203f7dba44e55332a5c5fae16d56e6aef400a1e27d901187d1671e3cbac5d5430b50ae0ffc67ed357d08245a65c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
